"""Add author_id column to café table

Revision ID: 2c5f58914e6a # Replace this with an appropriate revision ID
Revises: ced4ad73b77d
Create Date: 2023-08-04 11:16:24.992325

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2c5f58914e6a'  # Replace this with the generated revision ID
down_revision = 'ced4ad73b77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True),
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('map_url',
               existing_type=sa.TEXT(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.TEXT(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('seats',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('coffee_price',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_cafe_name', ['name'])  # Use a meaningful name like 'uq_cafe_name'

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_column('author_id')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('coffee_price',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=True)
        batch_op.alter_column('seats',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(length=500),
               existing_nullable=False)
        batch_op.alter_column('map_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(length=500),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
